export const Cities: string[] = [
  'Casablanca',
  'Marrakech',
  'Rabat',
  'Tangier',
  'Fez',
  'Agadir',
  'Fes',
  'Salé',
  'Meknes',
  'Oujda',
  'Kenitra',
  'Tetouan',
  'Temara',
  'Safi',
  'Mohammedia',
  'El Jadida',
  'Beni Mellal',
  'Khouribga',
  'Taza',
  'Settat',
  'Berrechid',
  'Nador',
  'Erfoud',
  'Dakhla',
  'Laayoune',
  'Ouarzazate',
  'Essaouira',
  'Al Hoceima',
  'Skhirat',
  'Guelmim',
  'Zagora',
  'Tiflet',
  'Larache',
  'Khenifra',
  'Berkane',
  'Taourirt',
  'Laghouat',
  'Oued Rhiou',
  'Souk Ahras',
  'Tissemsilt',
  'Laghouat',
  'Tamanrasset',
  'Ain Sefra',
  'Tindouf',
  'Reggane',
  'Béchar',
  'Adrar',
  'Bordj Bou Arréridj',
  'Tipasa',
  'Batna',
  'Blida',
  'Biskra',
  'Béjaïa',
  'Bou Saada',
  'Tebessa',
  'Tlemcen',
  'Constantine',
  'Djelfa',
  'El Bayadh',
  'Ghardaia',
  'Illizi',
  'Jijel',
  'Khenchela',
  'Mascara',
  'Médéa',
  'Mila',
  'Mostaganem',
  'Naâma',
  'Oran',
  'Ouargla',
  'Oum El Bouaghi',
  'Relizane',
  'Saida',
  'Sétif',
  'Sidi Bel Abbès',
  'Skikda',
  'Souk Ahras',
  'Tamanghasset',
  'Tébessa',
  'Tiaret',
  'Tindouf',
  'Tipaza',
  'Tissemsilt',
  'Tizi Ouzou',
  'Tlemcen',
  'El Oued',
  'El Tarf',
  'Tamanrasset',
  'Ghardaïa',
  'El M\'ghair',
  'El Meniaa',
  'Ouargla',
  'El Bayadh',
  'Ismailia',
  'Tebessa',
  'El Oued',
  'Khenchela',
  'Souk Ahras',
  'Tipaza',
  'Mila',
  'Aïn Defla',
  'Naâma',
  'Aïn Témouchent',
  'Guelma',
  'Khenchela',
  'Tissemsilt',
  'Relizane',
  'Ain Temouchent',
  'Djelfa',
  'Sidi Bel Abbes',
  'Tindouf',
  'M\'Sila',
  'Mascara',
  'Djanet',
  'Tebessa',
  'Adrar',
  'Khemis Miliana',
  'Souk Ahras',
  'Aïn Temouchent',
  'Tebessa',
  'Tindouf',
  'M\'Sila',
  'Sidi Bel Abbes',
  'Tizi Ouzou',
  'Mostaganem',
  'Khenchela',
  'Souk Ahras',
  'El Oued',
  'Relizane',
  'Djelfa',
  'Sidi Bel Abbes',
  'Tizi Ouzou',
  'Mostaganem',
  'Aïn Temouchent',
  'Tizi Ouzou',
  'Sidi Bel Abbes',
  'Tlemcen',
  'Mostaganem',
  'Djelfa',
  'Mostaganem',
  'Aïn Temouchent',
  'Aïn Temouchent',
  'Tlemcen',
  'M\'Sila',
  'Tlemcen',
  'Bordj Bou Arréridj',
  'Aïn Temouchent',
  'M\'Sila',
  'Tizi Ouzou',
  'Sidi Bel Abbes',
  'Djelfa',
  'Tlemcen',
  'Mostaganem',
  'Bordj Bou Arréridj',
  'Mostaganem',
  'Mostaganem',
  'Mostaganem',
  'Tlemcen',
  'Mostaganem',
  'M\'Sila',
  'Tlemcen',
  'Bordj Bou Arréridj',
  'Aïn Temouchent',
  'M\'Sila',
  'Tizi Ouzou',
  'Sidi Bel Abbes',
  'Djelfa',
  'Tlemcen',
  'Mostaganem',
  'Bordj Bou Arréridj',
  'Mostaganem',
  'Mostaganem',
  'Mostaganem',
  'Tlemcen',
  'Mostaganem',
  'M\'Sila',
  'Tlemcen',
  'Bordj Bou Arréridj',
  'Aïn Temouchent',
  'M\'Sila',
  'Tizi Ouzou'
]