import { Ticket } from "./ticket.model";
export const ticketData : Ticket[]=[
    {
      title: 'Le plus rapide',
      priceLabel: 'Prix',
      priceValue: 120,
      departureTime: '13:30',
      departureLocation: 'Marrakech',
      departureDay:'2024-06-11',
      travelDuration: '3h33min',
      arrivalTime: '18:00',
      arrivalLocation: 'Rabat',
      companyName: 'Ctm- ستيام',
      companyLogoSrc: '../../assets/icon/ctm-logo 1.svg',
      comfortLabel: 'confort',
      ticketNumberSrc: '../../assets/icon/number-1-rankings-georgia-tech-40 1.svg',
      expanded:false,
      totalSeats: 48,
      reservedSeats: [6, 7, 23, 9,8,12,22,23,13,1,25], // Example reserved seats
      selectedSeats: [],
      isTicketOpen: false
    },
    {
      title: 'Le plus tard',
      priceLabel: 'Prix',
      priceValue: 150,
      departureTime: '14:45',
      departureLocation: 'Marrakech',
      departureDay:'2024-06-11',
      travelDuration: '4h15min',
      arrivalTime: '19:00',
      arrivalLocation: 'Rabat',
      companyName: 'Supratours - سوبراتورز',
      companyLogoSrc: '../../assets/icon/oncf-logo.svg',
      comfortLabel: 'confort',
      ticketNumberSrc: '../../assets/icon/number-2-rankings-georgia-tech-40 1.svg',
      expanded:false,
      totalSeats: 48,
      reservedSeats: [5, 12, 33], // Example reserved seats
      selectedSeats: [],
      isTicketOpen: false
    },
    {
      title: 'Le plus cher',
      priceLabel: 'Prix',
      priceValue: 180 ,
      departureTime: '12:00',
      departureLocation: 'Agadir',
      departureDay:'2024-06-11',
      travelDuration: '6h30min',
      arrivalTime: '18:30',
      arrivalLocation: 'Oujda',
      companyName: 'Supratours - سوبراتورز"',
      companyLogoSrc: '../../assets/icon/supratours-logo.svg',
      comfortLabel: 'confort',
      ticketNumberSrc: '../../assets/icon/number-3-rankings-georgia-tech-40 1.svg',
      expanded:false,
      totalSeats: 48,
      reservedSeats: [5, 12, 23], // Example reserved seats
      selectedSeats: [],
      isTicketOpen: false
    },
    {
      title: 'Le moins cher',
      priceLabel: 'Prix',
      priceValue: 100,
      departureTime: '09:00',
      departureLocation: 'Fès',
      departureDay:'10/5/2024',
      travelDuration: '5h15min',
      arrivalTime: '14:15',
      arrivalLocation: 'Essaouira',
      companyName: 'Satas Group - مجموعة ساتاس"',
      companyLogoSrc: '../../assets/icon/tranatlas-logo.svg',
      comfortLabel: 'confort',
      ticketNumberSrc: '../../assets/icon/number-4-rankings-georgia-tech-40 1.svg',
      expanded:false,
      totalSeats: 48,
      reservedSeats: [5, 12, 23], // Example reserved seats
      selectedSeats: [],
      isTicketOpen: false
    },
    {
      title: '',
      priceLabel: 'Prix',
      priceValue: 135,
      departureTime: '11:30',
      departureLocation: 'Ouarzazate',
      departureDay:'10/5/2024',
      travelDuration: '4h45min',
      arrivalTime: '16:15',
      arrivalLocation: 'Tétouan',
      companyName: 'Trans Ghazala - نقل غزالة',
      companyLogoSrc: '../../assets/icon/ctm-logo 1.svg',
      comfortLabel: 'confort',
      ticketNumberSrc: '../../assets/icon/number-5-rankings-georgia-tech-40 1.svg',
      expanded:false,
      totalSeats: 48,
      reservedSeats: [5, 12, 23], // Example reserved seats
      selectedSeats: [],
      isTicketOpen: false
    },
    {
      title: '',
      priceLabel: 'Prix',
      priceValue: 95,
      departureTime: '08:15',
      departureLocation: 'Tanger',
      departureDay:'10/5/2024',
      travelDuration: '3h00min',
      arrivalTime: '11:15',
      arrivalLocation: 'Oujda',
      companyName: 'ALSA Morocco - السا المغرب"',
      companyLogoSrc: '../../assets/icon/oncf-logo.svg',
      comfortLabel: 'confort',
      ticketNumberSrc: '../../assets/icon/number-6-rankings-georgia-tech-40 1.svg',
      expanded:false,
      totalSeats: 48,
      reservedSeats: [5, 12, 23], // Example reserved seats
      selectedSeats: [],
      isTicketOpen: false
    },
    {
      title: 'Le plus rapide',
      priceLabel: 'Prix',
      priceValue: 120,
      departureTime: '13:30',
      departureLocation: 'Marrakech',
      departureDay:'10/5/2024',
      travelDuration: '3h33min',
      arrivalTime: '18:00',
      arrivalLocation: 'Rabat',
      companyName: 'Ctm- ستيام',
      companyLogoSrc: '../../assets/icon/ctm-logo 1.svg',
      comfortLabel: 'confort',
      ticketNumberSrc: '../../assets/icon/number-7-rankings-georgia-tech-40 1.svg',
      expanded:false,
      totalSeats: 48,
      reservedSeats: [5, 12, 23], // Example reserved seats
      selectedSeats: [],
      isTicketOpen: false
    },
    {
      title: 'Le plus tard',
      priceLabel: 'Prix',
      priceValue: 150,
      departureTime: '14:45',
      departureLocation: 'Casablanca',
      departureDay:'10/5/2024',
      travelDuration: '4h15min',
      arrivalTime: '19:00',
      arrivalLocation: 'Tanger',
      companyName: 'Trans Ghazala - نقل غزالة',
      companyLogoSrc: '../../assets/icon/oncf-logo.svg',
      comfortLabel: 'confort',
      ticketNumberSrc: '../../assets/icon/number-8-rankings-georgia-tech-40 1.svg',
      expanded:false, 
      totalSeats: 48,
      reservedSeats: [5, 12, 23], // Example reserved seats
      selectedSeats: [],
      isTicketOpen: false
    },
    {
      title: 'Le plus cher',
      priceLabel: 'Prix',
      priceValue: 180,
      departureTime: '12:00',
      departureLocation: 'Agadir',
      departureDay:'10/5/2024',
      travelDuration: '6h30min',
      arrivalTime: '18:30',
      arrivalLocation: 'Oujda',
      companyName: 'Trans Ghazala - نقل غزالة',
      companyLogoSrc: '../../assets/icon/supratours-logo.svg',
      comfortLabel: 'confort',
      ticketNumberSrc: '../../assets/icon/number-9-rankings-georgia-tech-40 1.svg',
      expanded:false,
      totalSeats: 48,
      reservedSeats: [5, 12, 23], // Example reserved seats
      selectedSeats: [],
      isTicketOpen: false
    },
    {
      title: 'Le moins cher',
      priceLabel: 'Prix',
      priceValue: 100,
      departureTime: '09:00',
      departureLocation: 'Fès',
      departureDay:'10/5/2024',
      travelDuration: '5h15min',
      arrivalTime: '14:15',
      arrivalLocation: 'Essaouira',
      companyName: 'Trans Ghazala - نقل غزالة"',
      companyLogoSrc: '../../assets/icon/tranatlas-logo.svg',
      comfortLabel: 'confort',
      ticketNumberSrc: '../../assets/icon/number-10-rankings-georgia-tech-40 1.svg',
      expanded:false,
      totalSeats: 48,
      reservedSeats: [5, 12, 23], // Example reserved seats
      selectedSeats: [],
      isTicketOpen: false
    },{
      title: 'Le plus rapide',
      priceLabel: 'Prix',
      priceValue: 120,
      departureTime: '13:30',
      departureLocation: 'Marrakech',
      departureDay: '10/5/2024',
      travelDuration: '3h33min',
      arrivalTime: '18:00',
      arrivalLocation: 'Rabat',
      companyName: 'ALSA Morocco - السا المغرب"',
      companyLogoSrc: '../../assets/icon/ctm-logo 1.svg',
      comfortLabel: 'confort',
      ticketNumberSrc: '../../assets/icon/number-11-rankings-georgia-tech-40 1.svg',
      expanded: false,
      totalSeats: 48,
      reservedSeats: [5, 12, 23], // Example reserved seats
      selectedSeats: [],
      isTicketOpen: false
    },
    {
      title: 'Le plus tard',
      priceLabel: 'Prix',
      priceValue: 150,
      departureTime: '14:45',
      departureLocation: 'Marrakech',
      departureDay: '10/5/2024',
      travelDuration: '4h15min',
      arrivalTime: '19:00',
      arrivalLocation: 'Rabat',
      companyName: 'Satas Group - مجموعة ساتاس"',
      companyLogoSrc: '../../assets/icon/oncf-logo.svg',
      comfortLabel: 'confort',
      ticketNumberSrc: '../../assets/icon/number-12-rankings-georgia-tech-40 1.svg',
      expanded: false,
      totalSeats: 48,
      reservedSeats: [5, 12, 33], // Example reserved seats
      selectedSeats: [],
      isTicketOpen: false
    },
    {
      title: 'Le plus cher',
      priceLabel: 'Prix',
      priceValue: 180,
      departureTime: '12:00',
      departureLocation: 'Agadir',
      departureDay: '10/5/2024',
      travelDuration: '6h30min',
      arrivalTime: '18:30',
      arrivalLocation: 'Oujda',
      companyName: 'Al Bidaoui Transport - البيضاوي للنقل',
      companyLogoSrc: '../../assets/icon/supratours-logo.svg',
      comfortLabel: 'confort',
      ticketNumberSrc: '../../assets/icon/number-13-rankings-georgia-tech-40 1.svg',
      expanded: false,
      totalSeats: 48,
      reservedSeats: [5, 12, 23], // Example reserved seats
      selectedSeats: [],
      isTicketOpen: false
    },
    {
      title: 'Le moins cher',
      priceLabel: 'Prix',
      priceValue: 100,
      departureTime: '09:00',
      departureLocation: 'Fès',
      departureDay: '10/5/2024',
      travelDuration: '5h15min',
      arrivalTime: '14:15',
      arrivalLocation: 'Essaouira',
      companyName: 'Trans Ghazala - نقل غزالة"',
      companyLogoSrc: '../../assets/icon/tranatlas-logo.svg',
      comfortLabel: 'confort',
      ticketNumberSrc: '../../assets/icon/number-14-rankings-georgia-tech-40 1.svg',
      expanded: false,
      totalSeats: 48,
      reservedSeats: [5, 12, 23], // Example reserved seats
      selectedSeats: [],
      isTicketOpen: false
    },
    {
      title: '',
      priceLabel: 'Prix',
      priceValue: 135,
      departureTime: '11:30',
      departureLocation: 'Ouarzazate',
      departureDay: '10/5/2024',
      travelDuration: '4h45min',
      arrivalTime: '16:15',
      arrivalLocation: 'Tétouan',
      companyName: 'Flecha - فليشا',
      companyLogoSrc: '../../assets/icon/ctm-logo 1.svg',
      comfortLabel: 'confort',
      ticketNumberSrc: '../../assets/icon/number-15-rankings-georgia-tech-40 1.svg',
      expanded: false,
      totalSeats: 48,
      reservedSeats: [5, 12, 23], // Example reserved seats
      selectedSeats: [],
      isTicketOpen: false
    }
  ];
  